/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package example.myevent;

import java.util.ArrayList;
import java.util.UUID;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;

/**
 *
 * @author Anastasia
 */
public class TimePanel extends javax.swing.JPanel implements IMyEvent{

  ArrayList<TimeClass> allTime = new ArrayList<>();
  Model m;
  DefaultListModel<String> l = new DefaultListModel< >();
  
  /**
   * Creates new form ViewPoint
   */


    public TimePanel() {
     initComponents();
    m = BModel.build(); 
    m.addObserver(this);


    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        SetSec = new javax.swing.JSpinner();
        SetMin = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jText = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        jButton1.setText("add");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("set seconds");

        jLabel2.setText("set minutes");

        jScrollPane1.setViewportView(jList1);

        jLabel3.setText("info");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(SetMin)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(SetSec)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jText)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jText, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SetMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SetSec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
                allTime = m.getP();
                int r =(int)SetSec.getValue() + ((int)SetMin.getValue()*60);
                int ind = allTime.size();
                allTime.add(new TimeClass(r, ind,jText.getText()));
                m.addDB(ind,r,jText.getText());
                m.setP(allTime);
                l.removeAllElements();
                for (TimeClass time:allTime){
                   // l.addElement("timer number " + time.getIndTime() + " sec: "+ time.getSec());
                    l.addElement("timer number " + time.getIndTime() + " time( " + setTime(time.getSec())+" )");

                }
                jList1.setModel(l);
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner SetMin;
    private javax.swing.JSpinner SetSec;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jText;
    // End of variables declaration//GEN-END:variables

    @Override
    public void timerMoved(Model m, UUID id) {
        allTime = m.getP();
        l.removeAllElements();
        for (TimeClass time:allTime){
            l.addElement("timer number " + time.getIndTime() + " time( " + setTime(time.getSec())+" )");
        }
        jList1.setModel(l);
    }

    @Override
    public void runEvent(ArrayList<TimeClass> p1,Model m, UUID id) {
        allTime = p1;
        for (TimeClass time:allTime){
           if(time.getFlag()){
               JOptionPane.showMessageDialog(this,
                       "Run event timer number "+ time.getIndTime() + " info "+ time.getInfo());
           }
        }

    }

    public String setTime(int s){

        StringBuilder str = new StringBuilder("00:");
        int m= s/60;
        s=s-(m*60);
        if(m<10){
            str.append("0").append(m);
        } else {
            str.append(m);
        }
        str.append(":");
        if(s<10){
            str.append("0").append(s);
        } else {
            str.append(s);
        }
        return str.toString();
    }
}
